### PR TITLE
fix(tsconfig): Allow default style import in the commonjs version build.

### LINKED ISSUE #53: Uncaught TypeError: Cannot read property 'getSync' of undefined
```
magickApi.js:78 Uncaught TypeError: Cannot read property 'getSync' of undefined
    at Object../node_modules/wasm-imagemagick/dist/src/magickApi.js (magickApi.js:78)
```

success after removing `.default` on line 78

### PR DESCRIPTION
**Pull request by Axure**
Fix #53

---
This change is [Reviewable](https://reviewable.io/reviews/knicknic/wasm-imagemagick/55)

### CODE REVIEW

**Comment by Axure** [comment]
@KnicKnic It seems that CI already failed at the "push 1.2.5" commit: https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/results?buildId=350

**Comment by KnicKnic** [comment]
> @KnicKnic It seems that CI already failed at the "push 1.2.5" commit with the same error: https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/results?buildId=350
> 
> It looks weird since nothing substantial was changed in that commit.

What is worse is that exact same commit built earlier, I simply rolled back to it....
https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/results?buildId=347 vs https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/results?buildId=350

**Comment by KnicKnic** [comment]
> @KnicKnic It seems that CI already failed at the "push 1.2.5" commit with the same error: https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/results?buildId=350
> 
> It looks weird since nothing substantial was changed in that commit.

@Axure thanks for bearing with the build issues.

Some package was updated in debian and the newer runs of apt-get install were causing issues. I fixed the base build in commit https://github.com/KnicKnic/WASM-ImageMagick/commit/755bfd6ea7139735b73d5d41fa1492437963b881 as I simply pushed an older container image I had built with the working versions. However tests still failed on your commit, see https://dev.azure.com/oneeyedelf1/wasm-imagemagick/_build/results?buildId=354&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=5caf77c8-9b10-50ef-b5c7-ca89c63e1c86&l=147 . Thanks!

**Comment by KnicKnic** [comment]
@Axure thanks for the detailed description you left of the fix in the issue. It was very helpful.

**Pull request merged**
