### PR TITLE
Typings

### PR DESCRIPTION
**Pull request by cancerberoSgx**
Solves project item "Add typescript typings to get syntax checking"

### CODE REVIEW

**Comment by cancerberoSgx** [comment]
Thank you ! I'm having lots of fun with your project lately. Good performance impression so far. I'm building some utilities and abstraction layer on top of it and I think you can find a couple of things interesting and perhaps intersecting this project 

https://github.com/cancerberoSgx/autumn-leaves/tree/master/imagemagick-browser

ignore the readme, what you have is: 

 1) higher level execute() function that can execute several commands remembering the output files so they can be used in following commands
 2) typings (enums) for all IM list types **automatically generated** by executing `convert -list morphology` (for example) . Generated code : https://github.com/cancerberoSgx/autumn-leaves/tree/master/imagemagick-browser/src/list
 . Automation : https://github.com/cancerberoSgx/autumn-leaves/blob/master/imagemagick-browser/scripts/generateImEnums.ts
3) utilities for parsing CLI options to array format, extracting image information (executing convert foo.png json:foo.json), and utilities to  handle array, blobs, input elements (in general to easily handling the types (MagickInputFile and MagickOutputFile)

I "believe" in unix philosophy and I think your project should only be responsible of providing the call() function (as it doing now) so I'm not sure if the mentioned things should be integrated on it or if they should be in a separate project (like mine). But perhaps some stuff, in particular the enums could make sense. What do you think - Would be great to know your opinion

BTW I have new toys : 

 * image transformation UI : https://cancerberosgx.github.io/autumn-leaves/#/home
 * encypher images: https://cancerberosgx.github.io/autumn-leaves/#/encipher
 * extract information : https://cancerberosgx.github.io/autumn-leaves/#/imageInformation
 
I didn't put attention to the UI but building tools like this (and other ideas) with a nice UI would help this project to be known by more people. BTW did you announced this project somewhere ? at least to the imagemagick team ? 

Thanks, keep it up - sorry for the long msg

**Comment by KnicKnic** [comment]
I have posted to the imagemagick developers forum [link](https://imagemagick.org/discourse-server/viewtopic.php?f=2&t=34362&p=157637&hilit=webassembly#p157637). Asking about short file names bug I hit (the one real thing I wish was fixed). As well as another response t to a person asking about iphone development where I suggested they could use this project and just write a PWA (the whole thread was deleted, not just my post). I have been permanently banned from the forum.
Another place I did mention it at was https://github.com/kripken/emscripten/wiki/Porting-Examples-and-Demos .

I really like all the typings. I have no problem if you want to enhance this project with those apis. I think it would make sense to have one project. The biggest issue would only be about overcrowding the initial readme between advanced and simple usage, to give them enough information to break out into the appropriate place and not scare them off, or have them leave unimpressed.

The project has pretty much served my purpose and culminated in the following [youtube video](https://www.youtube.com/watch?v=94fdgtDT1XI) where use it by writing a bookmarklet to extend webtoons.com website to autoconvert people's image upload into the right formats. 

I really like how you have extended things and the pages you have built with it. Thanks for helping me with NPM & typescript. Would you want push access to this git & the NPM project?

**Comment by cancerberoSgx** [comment]
I would love to see this project in this list https://imagemagick.org/script/develop.php

>  I have been permanently banned from the forum.

Wow, this people still use forums? and you were banned ? Aja, good signal not to register myself in there. I had some luck in github project https://github.com/ImageMagick/ImageMagick for example, I reported a small issue and they already fixed it: https://github.com/ImageMagick/ImageMagick/issues/1333

I've noticed that they have some examples in the docs that I cannot find in the repos sources. Let me try to familiarize with the sources and figure out how we can add some links to this project in there - it really deserve it! I think it has great potential. I'm using my projects in an iphone5 with no-small images and its working acceptably (most of the time). I want to refine and design the UI better before I push the projects. 

If I cannot/dunnot know how to make the PR to "anounce" this project, then I'll try to build a good demo site, with a good design  demonstrating different transformations and a playground and then report them an issue asking to add just need to report an issue with a t

> The project has pretty much served my purpose and culminated in the following...

That's it mean that you won't maintain it anymore? Or don't have any plans / features for the future ? You sound like no motivation, if so I'm having lots of simple ideas for webpages using it that could be very fun to build and who knows :)  

I would like to ask a couple of questions mostly regarding the libraries you have forked: 

 * Mostly I wonder how easy it's to upgrade imagemagick and its libraries. I see that you needed to make some changes in libpng, libjpg and imagemagick. I cannot understand what were the changes in this one: 
https://github.com/LuaDist/libjpeg/compare/master...KnicKnic:master Perhaps you or your editor just indented all those files ? or you really made changes there ? 

 * What happen if you don't patch any of the libraries ? just won't work at all ? I understand your changes in ImageMagick repo to bypass library checkings but I'm concerned why did you need to patch the actual .c sources of libs (ilke https://github.com/glennrp/libpng/compare/libpng16...KnicKnic:libpng16)

 * Is OK if I start reporting issues with things that I don't understand or details so we keep track in  the future ? Can I add some project cards for me? Can I try to tackle a couple of existing issues (mostly mine regarding flexibility to load .wasm file from any url - I think that's important)

 * I tried to add freetype library support (https://github.com/cancerberoSgx/WASM-ImageMagick/tree/freetype) but it seems convert try to spawn `gs` program and of course that will never work in the browser so I give up. My next step will  be trying to add support to webp I will track this work in an issue.   

> Would you want push access to this git & the NPM project?

Yes please! git would be enough I can publish the project but I think you as the author should do it . 

Your reply motivate me to migrate a couple of things from my project to your's. WIll start with IM enums. That would facilitate things for me :)

Also don't know if already mentioned it to you but in my project I have some tests in the browser (using puppeteer) I think this project should too. WiIl try to migrate some of that infrastructure here, ok?

Just out of curiosity, do you work at Microsoft ? 

See you

**Comment by ohenepee** [comment]
What happened to the WebP support?

**Comment by cancerberoSgx** [comment]
unlike last time I checked, seems several example of porting libwebp to emscripten, unfortunaty, personally I don't have much time for it but it seems straighforward:

 * https://medium.com/@kennethrohde/on-the-fly-webp-decoding-using-wasm-and-a-service-worker-33e519d8c21e
 * https://github.com/kenchris/wasm-webp
 * https://github.com/proxytype/wasm-webp

**Comment by KnicKnic** [comment]
I suggest you use https://github.com/dlemstra/Magick.Native which has webp support

**Comment by cancerberoSgx** [comment]
@KnicKnic  that is very interesting, but has no docs, do you know if they are reusing/translating IM sources or how much they if/had to write from scratch ? thanks for the link!

**Comment by KnicKnic** [comment]
dlemstra had a better position with understanding the compile process from previous work on imagemagick. I do know that they took my code as a starting block for that project however. My understanding is that the project pulls the imagemagick codebase in, and it is not a forked one. 

The reason I have a forked imagemagick code base was I couldn't understand the compile flags to get certain specific options enabled in the codebase. My guess is dlemstra did.

Some of the dependency projects like libpng that I forked due to incompatibilities with webassembly (function ptr mismatch) (I never bothered to get the changes clean enough to submit upstream).

**Comment by cancerberoSgx** [comment]
aja, Wonder what do you think about the future of this project ? or how the two relates. Personally I don't think is important to be up to date with current supported image formats - they won't add new features - probably only stability/performance/compatibility only. I suspect they have little activity (zip, libpng, tiff, jpg, etc). About ImageMagic, I know it for about 10-15 years and far as I remember I didn't see new features (do you?) - probably it improved in performance - compatibility - (?) -- see emscripten ports for zlib, libpng (last updated in 2015) https://github.com/emscripten-ports. 

BTW recently I found this initiative https://wapm.io/ (WebAssembly Package Manager) which is like npm for wasm projects , still very new and few package. Not sure if it's a good idea to manage packages outside npm but it's nice to see a collection/gallery of wasm packages.  

Now I see  somebody take the initiative with this project: 

 * https://wapm.dev/package/imagemagick
 * https://github.com/wapm-packages/imagemagick

Personally I'm not sure I like this . Maybe is a good idea to promote the package manager also I think authors should be able to be the first person deciding to publish or not a repository before others fork and publish. What do you think? 

Will research more - sorry for the noise and so arbitrary topics...

**Comment by KnicKnic** [comment]
# Current State
Reasons I use ImageMagick
1. Had all options I wanted and was easy to use
1. Supported most image formats I wanted
    * PNG, JPEG, TIFF, PSD
    * biggest next format I want is .clip (it is however a proprietary format)
1. Great photoshop compatibility
    * Other solutions I found didn't have the same level.

Downsides I know of compare to some other solutions are 
1. Uses a lot of CPU
1. Uses a lot of RAM
    * this is the biggest issue for me
1. Doesn't have a great native javascript api

# Future
## Api
Honestly I see https://github.com/dlemstra/Magick.Native  as solving the last one. However as you said, the project could be more approachable. I currently lack the motivation to invest in any project in this area substantially. I am okay for maintenance tasks, moving PR's along. Basic issues. Release is Automated, so I do not have to worry about that.

## cmdline
I am not sure that https://github.com/dlemstra/Magick.Native aims to solve this. But it was also a nice feature of this project. A website where you can give people a cmdline to process their images; https://knicknic.github.io/imagemagick/ this is one place I could see it being nice to support more image formats.

This is also how the wapm package is using it.

# Packaging
## ~~Size~~
Since Imagemagick is so heavy it would be nice if the delegates were lazily loaded. I think over half the assembly size is just imagemagick however. Meaning you don't save tons by lazily loading. You can get great wins by caching the binary on the client via serviceworkers, largely removing this as an issue
## Internet
 Frankly I like to view webassembly like your CPU and the internet like your file system. It would be great if everything were modules on the internet, and shared so could be reused by multiple sites. Inevitably testing gets in the way, and you end up with little shared as everyone uses the version they signed off with. (I know wasmer sees opportunity to run webassembly outside the browser)

However in the above vain I do maintain a place where I put the most recent version of ImageMagick webassembly such that it can be easily loaded (**not versions**) allowing you to just 
```js
import * as Magick from 'https://knicknic.github.io/wasm-imagemagick/magickApi.js';
```

# Forks / Opensource
I love that developers are using the code in ways that work for them. I do wish code is centralized in as few places as possible. @syrusakbary is there any way to merge your code back in. Currently I will not take a pull request as you checked in a magick.wasm binary and I do not think that artifacts belong in the source tree and that is what releases are for. I can make another release. 

Ultimately if you want the binary generation to be in the hands of wasmer the easiest option I see is you setting up a CICD pipeline and letting me download the artificats from that location. Or you can trust the one I setup azure pipelines. I am not sure how auditable they are, but I do grab my artificats from there. Then you would use a secure cryptographic hash to validate the binaries in wamp. I couldn't understand how repository management is done for wapm, would this be possible?

@syrusakbary is there a specific reason that you are maintaining an organization of forks for wapm?

**Comment by syrusakbary** [comment]
Thanks for the ping @KnicKnic.

> @syrusakbary is there any way to merge your code back in

I would love to merge [the wapm fork](https://github.com/wapm-packages/imagemagick).
The main reason we haven't done it yet is because the `magick.wasm` file was not yet working with wasmer (we are working on it). Once it's officially working, I'll create a PR into this repo with your suggestions :)

> Ultimately if you want the binary generation to be in the hands of wasmer the easiest option I see is you setting up a CICD pipeline and letting me download the artificats from that location

I think that's a great idea. Let's chat once magick.wasm runs in wasmer so I can make sure this use case is covered.

> Then you would use a secure cryptographic hash to validate the binaries in wapm. 

We are working on package signing in [wapm](https://wapm.io). This way the packages can't be tampered in any way. In about a week or less we will publish the article on how to use it.

> @syrusakbary is there a specific reason that you are maintaining an organization of forks for wapm?

Yes, mainly because not all the maintainers of the repos want the wapm changes upstream, but we still want to make them available on wapm. Overtime I foresee the number of packages in wapm-packages moving towards 0 🤞

Hope this clarifies things!

**Comment by cancerberoSgx** [comment]
@KnicKnic 
> with. (I know wasmer sees opportunity to run webassembly outside the browser)

In my experience WASM and cia was one of the mose intersting experices. The painful parts for someone that don't write a a line of Something that needs to be compiled was, as author maintaining / debugging / wasm projects. But I see some people do it painless. 

Where I didn't saw any good solution was for the user to have a good install experience. In generalyou alwasy need to luckly just manually coping wasm files but in general generating them. And lots of people refuce being forced to do it or install docker or wsdk for building frontend. 
Really that's why an idea like  wesmer could be a good one. I tried to register but it didn't let me login nor send me the password by email so I guess is broken hopully temporarily. For some commands like see owners you need to login. 

What I dislike is that this kind of projects, first of all, need to be transparent, with a clear policy and better one copied or owned by a known trusted actor, like npm.

In summary I think wasm projects authors are missin aplace to store those big files. And Iwonder why they just not use npm ? In npm you don't store sources, you store bynaries. so it makes totally sense to me. 

For what you mention perhaps wasmer is doing it the other way around storing  binaries in in the git repo ? I'm consumin a couple of projecs written in rust , c++, etc with scripts for generate wasm and I currenlty also store those in my .git repo since are private not meant tobe published.

> Then you would use a secure cryptographic hash to validate the binaries in wamp.

Again, why not use npm for .wasm that as you mention already solves those problems and again is for artifacts not for code ?  

> import * as Magick from 'https://knicknic.github.io/wasm-imagemagick/magickApi.js';

can I trust will have latest version ? :P

The saddest think I saw regarding the open source community is a certain project, unique in its class, tackling a not ordinary problem  which author which is brilliant go to find other battles and how people desperates in issues and forks the fork of the forks and you know how hard to understand  and how little could be a briliant engineer code and documentation... And on he other hand  I see so many repeated projects, over-promotionated competing for intelligent phrases, icons and logos, all in phrases and logos, to see which complies better with the current trending topic,, tight in the same poduim, with hands up, shouting to be most responsive, awesome and liquid, and there in silence, surrounded by user tears, unresponsive issues and dry markdown, with its hundred unattended pull requests, but more than alive, as it will after ten generations of "state-of-the-art" passed by, all by it self, by its code, by its problem, by it countless desperate users for which is not given even resignation.

**Comment by KnicKnic** [comment]
@cancerberoSgx I will update the docs to point to a npm instead of my github. My understanding is I have to go through a cdn like unpkg (any recommendations here?).

Also my releases script broke.... I fixed it, hopefully it releases now and I will test the docs and update them against the new location.

**Comment by KnicKnic** [comment]
So I tested switching to a cdn and... it didn't work in edge beta(chromium version). it works in edge, firefox, chrome...
I tested 2 cdns.
1. https://unpkg.com
    * does not work due to wrong mime type on wasm files
1. https://jsdelivr.net
    * fails to fetch the wasm file due to a type error
    * has correct mime type

broken page is https://knicknic.github.io/imagemagick/rotate/index.cdn.html

**Pull request merged**
